// Generated by CoffeeScript 1.10.0
(function() {
  var Client, ClientSocket, NGINX_DIR, Server, ServerSocket, events, settings, vhostr;

  events = require("events").EventEmitter;

  vhostr = require("nginx-vhosts");

  ServerSocket = require("socket.io");

  ClientSocket = require("socket.io-client");

  NGINX_DIR = "/etc/nginx";

  settings = {
    port: 80,
    nginx: {
      confDir: '/etc/nginx/conf.d/',
      pidLocation: '/var/run/nginx.pid'
    }
  };

  Server = (function() {
    function Server(options) {
      if (options == null) {
        options = settings;
      }
      this.nginx = vhostr(settings.nginx);
      this.httpServer = http.createServer(function(req, res) {
        return res.status(200).send('online');
      });
      this.httpServer.listen(settings.port, function() {
        return console.log("listening on " + settings.port);
      });
      this.io = ServerSocket.listen(this.httpServer);
      this.events = events;
      this.io.on('connection', function(socket) {
        console.log('client connected');
        return socket.on('disconnect', function() {
          return console.log('client disconnected');
        });
      });
      return this;
    }

    return Server;

  })();

  Client = (function() {
    var connect;

    function Client(host, port) {
      if (host == null) {
        host = "localhost";
      }
      if (port == null) {
        port = 80;
      }
      this.io = ClientSocket;
      this.socket = new io.Socket(host, {
        port: port
      });
      this.socket.on("connect", function() {
        return console.log("connected to " + host + ":" + port);
      });
      return this;
    }

    connect = function() {
      return this.socket.connect();
    };

    return Client;

  })();

  module.exports = {
    Client: Client,
    Server: Server
  };

}).call(this);

//# sourceMappingURL=router.js.map
